# Generated by Django 3.2.13 on 2022-06-18 22:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.IntegerField(unique=True, verbose_name='Número de mesa')),
                ('is_available', models.BooleanField(default=False, verbose_name='Disponibilidad')),
                ('qr_identifier', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Identificador QR')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
    ]
