# Generated by Django 3.2.13 on 2022-05-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_identifier',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Identificador QR'),
        ),
    ]
