# Generated by Django 3.2.13 on 2022-06-18 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_type', models.CharField(choices=[('0', 'EFECTIVO'), ('1', 'TARJETA DE CRÉDITO/DEBITO')], default=0, max_length=20, verbose_name='Tipo de pago')),
                ('payment_status', models.CharField(choices=[('0', 'PENDIENTE'), ('1', 'PAGADO')], default=0, max_length=15, verbose_name='Estado del pago')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
